### PR TITLE
wording now consitently in English

### PR DESCRIPTION
**Pull request by 00Bock**

### CODE REVIEW

**Comment by BenSto** [comment]
Please make a comment when opening a pull request. Like ```please do not merge into master. This is an approach to develop a language switch.```

Because the way it is now. No one knows if this can be merged or if this is working. I think that you just replaced the german strings with english ones, so that we just have an english page, but no more german. Which is not what we need. Furthermore when I see it correctly the specs are broken now.

**Comment by BenSto** [comment]
But we can keep the english translation so that the work is a good start!

**Comment by 00Bock** [comment]
Ok. I forgot that part with the classification in 'wip' or 'ready to delete'. So I run the 
`bundle exec rake db:migrate `
command. I thought that was kind of like running the specs but I now see, that the migrate command was one too much. 

When running the specs, you can see that really I just did not translate the yaml `de:
  learn_more: 'Mehr erfahren'`. So I guess is to complete that file for all text blocks and place something like `= t('learn_more')` where currently textblocks are?

In the end, the issue still comes back to issue #15 and the question if we want an English or a German entry page. I prefer the first... In the moment, when you enter http://127.0.0.1:3000/ you get the words "Mehr erfahren" and the switch 'switch to English'. But it should redirect to http://127.0.0.1:3000/de and get the words "Mehr erfahren" and the switch 'switch to English'. Under http://127.0.0.1:3000/ you should get the words "Learn more" and the switch 'zur deutschen Version' or get redirected to http://127.0.0.1:3000/en and see the words "Learn more" and the switch 'zur deutschen Version'. I don't know what scenario of the last two is less complicated, more common, tidier. Does that make sense?

**Comment by 00Bock** [comment]
Oh... no I'm confused. The situation in the master branch is ok with http://127.0.0.1:3000/ showing the words "Learn more" and the switch 'zur deutschen Version'

**Comment by kjoscha** [comment]
okay, if i got it right, there is only the decision about the default language? I think there is enough time left to decide it. In the end, it is only one line of code and the page is not as close to launch yet. Maybe this is an issue for a meeting...

**Comment by 00Bock** [comment]
:+1:

**Pull request closed without merging**
