### PR TITLE
adding English text to example Radspurenleser

### PR DESCRIPTION
**Pull request by 00Bock**
ready to merge. Rake test failed:

```
     Failure/Error: Capybara.page.driver.browser.resize(1600, 1000)
     
     Cliver::Dependency::NotFound:
       Could not find an executable ["phantomjs"] on your path.
```

I don't think that's because of my changes...

### CODE REVIEW

**Comment by BenSto** [comment]
When specs ar failing, never merge ;-) . It seems like you are missing phantomjs... as the message already stated. Maybe follow this introduction to fix your problem
https://gist.github.com/julionc/7476620

**Comment by 00Bock** [comment]
Danke. Ging nun mit zero failures. ein wunder

**Comment by BenSto** [comment]
> Danke. Ging nun mit zero failures. ein wunder

:pray:

**Comment by kjoscha** [comment]
thanks

**Pull request merged**
